### ISSUE TITLE
Sprint 1 Feedback

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/c346-34515-fa22-project-magicllamas#18]
This looks fine to me.

- Please remove minutes.md from the root of the project. It is only supposed to be a template for the actual minutes files in doc.
- Small nitpick: You have a markdown error in your readme. The `##` need a space after them on the Features heading.
- Have you verified/found a library for connecting/interacting with the Discord API in Java? I'd be looking real hard and careful at that and the quality of what you find. You may find that you wish you had used something else for ease of development. (javascript is popular, go is great, etc) No need to change if you have something in mind, but I'd verify that _fast_.

You can close this issue after you fix the first two problems.

**Comment by ImaniChristianne** [comment]
Issues are fixed.
